### PR TITLE
Upgrade dependencies and modernize code for 2018 edition

### PR DESCRIPTION
**Pull request by mitsuhiko**
We're using this in sentry-cli and this pulls in a really old version of rand. This upgrades the dependency and I also modernized the crate in the process.

### CODE REVIEW

**Comment by ihrwein** [comment]
@mitsuhiko  thank you for your work!

**Comment by ihrwein** [comment]
I'll make a new release tonight.

**Comment by ihrwein** [comment]
@mitsuhiko I've cut a 0.1.3 release. Thanks again for the updates!

**Comment by mitsuhiko** [comment]
Thanks for the fast turnaround, upgraded immediately: https://github.com/getsentry/sentry-cli/commit/3fb080e9f10be0d8d171fc38f58f4b27f800143a :)

**Pull request merged**
